title: Jason Djajasasmita # your name (or website title) here
logo: "/images/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  "Hi i'm Jason, I am a student currently pursuing a Bachelor's degree in Computer Science" 
  <br><br>
  This is where i document the projects i've worked on  
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
